// src/components/pages/archivo/CountUp.vue
<script setup>
import { ref } from 'vue'
import ProgressiveNumber from "./ProgressiveNumber";

const { initial, final, duration, decimals } = defineProps({
  initial: {
    type: Number,
    required: true
  },
  final: {
    type: Number,
    required: true
  },
  decimals: {
    type: Number,
    default: 0
  },
  duration: {
    type: Number,
    default: 1500
  }
})

const count = ref(initial)

ProgressiveNumber.generate(
  initial,
  final,
  (value) => {
    count.value = value;
  },
  duration,
  decimals
);
</script>

<template>
  <span>{{ count }}</span>
</template>

// src/components/pages/archivo/CountUp.svelte
<script setup>
import ProgressiveNumber from "./ProgressiveNumber";

export let initial;
export let final;
export let decimals = 0;
export let duration = 1500;

let count = 0

ProgressiveNumber.generate(
  initial,
  final,
  (value) => {
    count = value;
  },
  duration,
  decimals
);
</script>

<span>{ count }</span>
