// src/components/CountUp.tsx
import { useProgressiveNumber } from '@/hooks/useProgressiveNumber'
import { useEffect} from 'preact/hooks'

export const CountUp = (
  { initial, final, decimals, duration }:
  { initial: number, final: number, decimals?: number, duration?: number }
) => {
  const [count, setCount] = useProgressiveNumber(initial, duration, decimals)

  useEffect(() => {
    setCount(final)
  }, [final])

  return <span>{count}</span>
}

// src/components/pages/archivo/CountUp.svelte
<script setup>
import ProgressiveNumber from "./ProgressiveNumber";

export let initial;
export let final;
export let decimals = 0;
export let duration = 1500;

let count = 0

ProgressiveNumber.generate(
  initial,
  final,
  (value) => {
    count = value;
  },
  duration,
  decimals
);
</script>

<span>{ count }</span>
