// src/components/Count/Up.svelte
<script setup>
import ProgressiveNumber from "./Up";

export let initial;
export let final;
export let decimals = 0;
export let duration = 1500;

let count = 0

ProgressiveNumber.generate(
  initial,
  final,
  (value) => {
    count = value;
  },
  decimals,
  duration
);
</script>

<span>{ count }</span>

// src/components/Count/Up.vue
<script setup>
import { ref } from 'vue'
import ProgressiveNumber from "./Up";

const { initial, final, duration, decimals } = defineProps({
  initial: {
    type: Number,
    required: true
  },
  final: {
    type: Number,
    required: true
  },
  decimals: {
    type: Number,
    default: 0
  },
  duration: {
    type: Number,
    default: 1500
  }
})

const count = ref(initial)

ProgressiveNumber.generate(
  initial,
  final,
  (value) => {
    count.value = value;
  },
  decimals,
  duration,
);
</script>

<template><span>{{ count }}</span></template>
