// src/components/Link.vue
<script setup lang="ts">
interface Props {
  href: string
  locale?: string
}

import { getRelativeLocaleUrl } from "@/i18n/config"

const props = defineProps<Props>()
let { href, locale } = props;
href = getRelativeLocaleUrl(locale, href)
</script>

<template>
  <a :href=href><slot></slot></a>
</template>

// src/components/Link.tsx
interface Props {
  href: string
  children?: preact.ComponentChildren
  locale?: string
  className?: string
}

import { getRelativeLocaleUrl } from "@/i18n/config" // falla si no esta dentro

export default ({ href, locale, children, ...rest }: Props) => {
  return <a href={getRelativeLocaleUrl(locale, href)} {...rest}>{children}</a>
}
